# Postgres Database
# A standalone Postgres database configured to work with Supabase services.
database:
  # enabled: false Disable the database provisioning
  postgresqlPassword: PostGreSQL123
  persistence:
    storageClass: csi-disk

studio:
  # enable: false # Disable the studio
  environment:
    SUPABASE_URL: http://api.localhost
    STUDIO_PG_META_URL: http://supabase-kong.supabase.svc.cluster.local:8000/pg
    SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UiLAogICAgImlhdCI6IDE2NjEyMDIwMDAsCiAgICAiZXhwIjogMTgxODk2ODQwMAp9.MThJSRY_lgzgwur9Qqr1SQfVB8AO-E_y0-V6AvKdFlI"
    SUPABASE_SERVICE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJzZXJ2aWNlX3JvbGUiLAogICAgImlzcyI6ICJzdXBhYmFzZSIsCiAgICAiaWF0IjogMTY2MTIwMjAwMCwKICAgICJleHAiOiAxODE4OTY4NDAwCn0.91l79tCG8D1Tq0Qa_pNKX7aze2bPQIUnmql-IUCEH_Q"

  ingress:
    enabled: 'true'
    className: ""
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/elb.port: '80' 
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: studio.localhost
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: api
              servicePort: 3000

# Auth Service
auth:
  environment:
    GOTRUE_DB_DATABASE_URL: postgres://postgres:PostGreSQL123@supabase-database.supabase.svc.cluster.local:5432/postgres?search_path=auth
    GOTRUE_SITE_URL: http://studio.localhost
    GOTRUE_URI_ALLOW_LIST: ""
    GOTRUE_DISABLE_SIGNUP: "false"
    GOTRUE_JWT_SECRET: "sTfSgSSCi80zJvdQugIg6S8Cd8klthKt0okIk27rN7muBH5Q59nh8+ribSep4+F+NlVMhZreh9BFxqZNah7KpQ=="
    GOTRUE_JWT_EXP: "3600"
    GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
    GOTRUE_MAILER_AUTOCONFIRM: "true"
    GOTRUE_SMTP_ADMIN_EMAIL: "admin@example.com"
    GOTRUE_SMTP_HOST: "mail"
    GOTRUE_SMTP_PORT: "2500"
    GOTRUE_SMTP_USER: "fake_mail_user"
    GOTRUE_SMTP_PASS: "fake_mail_password"
    GOTRUE_SMTP_SENDER_NAME: "fake_sender"
    GOTRUE_EXTERNAL_PHONE_ENABLED: "false"
    GOTRUE_SMS_AUTOCONFIRM: "false"

# Rest Service
rest:
  environment:
    PGRST_DB_URI: postgres://postgres:PostGreSQL123@supabase-database.supabase.svc.cluster.local:5432/postgres
    PGRST_JWT_SECRET: "sTfSgSSCi80zJvdQugIg6S8Cd8klthKt0okIk27rN7muBH5Q59nh8+ribSep4+F+NlVMhZreh9BFxqZNah7KpQ=="

# Realtime Service
realtime:
  environment:
    DB_HOST: supabase-database.supabase.svc.cluster.local
    DB_PORT: "5432"
    DB_NAME: postgres
    DB_USER: postgres
    DB_PASSWORD: PostGreSQL123
    DB_SSL: "false"
    JWT_SECRET: "sTfSgSSCi80zJvdQugIg6S8Cd8klthKt0okIk27rN7muBH5Q59nh8+ribSep4+F+NlVMhZreh9BFxqZNah7KpQ=="

# Meta Service
meta:
  environment:
    PG_META_DB_HOST: supabase-database.supabase.svc.cluster.local
    PG_META_DB_PASSWORD: PostGreSQL123

# Storage Service
storage:
  environment:
    ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UiLAogICAgImlhdCI6IDE2NjEyMDIwMDAsCiAgICAiZXhwIjogMTgxODk2ODQwMAp9.MThJSRY_lgzgwur9Qqr1SQfVB8AO-E_y0-V6AvKdFlI"
    SERVICE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJzZXJ2aWNlX3JvbGUiLAogICAgImlzcyI6ICJzdXBhYmFzZSIsCiAgICAiaWF0IjogMTY2MTIwMjAwMCwKICAgICJleHAiOiAxODE4OTY4NDAwCn0.91l79tCG8D1Tq0Qa_pNKX7aze2bPQIUnmql-IUCEH_Q"
    POSTGREST_URL: http://supabase-rest.supabase.svc.cluster.local:3000
    PGRST_JWT_SECRET: "sTfSgSSCi80zJvdQugIg6S8Cd8klthKt0okIk27rN7muBH5Q59nh8+ribSep4+F+NlVMhZreh9BFxqZNah7KpQ=="
    DATABASE_URL: postgres://postgres:PostGreSQL123@supabase-database.supabase.svc.cluster.local:5432/postgres
    PGOPTIONS: -c search_path=storage,public
  persistence:
    storageClassName: "csi-disk"

# Kong Service (API Gateway)
kong:
  ingress:
    enabled: 'true' 
    className: ""
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/elb.port: '80'
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: api.localhost
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: api
              servicePort: 80
    credentials:
      anonKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UiLAogICAgImlhdCI6IDE2NjEyMDIwMDAsCiAgICAiZXhwIjogMTgxODk2ODQwMAp9.MThJSRY_lgzgwur9Qqr1SQfVB8AO-E_y0-V6AvKdFlI"
      serviceRoleKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJzZXJ2aWNlX3JvbGUiLAogICAgImlzcyI6ICJzdXBhYmFzZSIsCiAgICAiaWF0IjogMTY2MTIwMjAwMCwKICAgICJleHAiOiAxODE4OTY4NDAwCn0.91l79tCG8D1Tq0Qa_pNKX7aze2bPQIUnmql-IUCEH_Q"